sudo: false
language: python
cache: pip
matrix:
  include:
    - env: TOXENV=py27-django18
      python: 2.7
    - env: TOXENV=py34-django18
      python: 3.4
    - env: TOXENV=py35-django18
      python: 3.5
    - env: TOXENV=py27-django19
      python: 2.7
    - env: TOXENV=py34-django19
      python: 3.4
    - env: TOXENV=py35-django19
      python: 3.5
    - env: TOXENV=py27-django110
      python: 2.7
    - env: TOXENV=py34-django110
      python: 3.4
    - env: TOXENV=py35-django110
      python: 3.5
    - env: TOXENV=py27-django111
      python: 2.7
    - env: TOXENV=py34-django111
      python: 3.4
    - env: TOXENV=py35-django111
      python: 3.5
    - env: TOXENV=py36-django111
      python: 3.6
    - env: TOXENV=py34-django20
      python: 3.4
    - env: TOXENV=py35-django20
      python: 3.5
    - env: TOXENV=py36-django20
      python: 3.6
    - env: TOXENV=py35-django21
      python: 3.5
    - env: TOXENV=py36-django21
      python: 3.6
install:
  - pip install tox
script:
  - tox
after_success:
  - pip install codecov
  - coverage report
  - codecov